### ISSUE TITLE
Framework/tool mismatch

### ISSUE THREAD

**Issue by SilverFoxA** [thakurankit6767/mozaicq_frontend#1]
@thakurankit6767 Overall, the site looks great. Please list the technologies used to design the site.

**Comment by thakurankit6767** [comment]
Html css javascript

**Comment by SilverFoxA** [comment]
Did you use Webflow to build the site?

**Comment by thakurankit6767** [comment]
No

**Comment by SilverFoxA** [comment]
![Screenshot 2023-02-28 at 10 32 26 AM](https://user-images.githubusercontent.com/6983070/221758778-22b2fe41-fe91-4d47-9cb6-d67853d1c50b.png)
